sudo: false
language: ruby
cache: bundler
before_install:
  - gem i rubygems-update -v '<3' && update_rubygems
  - gem update bundler
gemfile:
  - Gemfile
  - gemfiles/rails_4_1.gemfile
  - gemfiles/rails_4_2.gemfile
  - gemfiles/rails_5_0.gemfile
  - gemfiles/rails_5_1.gemfile
  - gemfiles/rails_5_2.gemfile
  - gemfiles/rails_6_0.gemfile
  - gemfiles/rails_6_1.gemfile
rvm:
  - "2.1"
  - "2.2"
  - "2.3.4"
  - "2.4.0"
  - "2.4.1"
  - "2.5"
  - "2.6"
  - "2.7"
matrix:
  exclude:
    - rvm: "2.1"
      gemfile: gemfiles/rails_5_0.gemfile
    - rvm: "2.2"
      gemfile: gemfiles/rails_5_0.gemfile
    - rvm: "2.1"
      gemfile: gemfiles/rails_5_1.gemfile
    - rvm: "2.2"
      gemfile: gemfiles/rails_5_1.gemfile
    - rvm: "2.1"
      gemfile: gemfiles/rails_5_2.gemfile
    - rvm: "2.2"
      gemfile: gemfiles/rails_5_2.gemfile
    - rvm: "2.1"
      gemfile: gemfiles/rails_6_0.gemfile
    - rvm: "2.2"
      gemfile: gemfiles/rails_6_0.gemfile
    - rvm: "2.3.4"
      gemfile: gemfiles/rails_6_0.gemfile
    - rvm: "2.4.0"
      gemfile: gemfiles/rails_6_0.gemfile
    - rvm: "2.4.1"
      gemfile: gemfiles/rails_6_0.gemfile
